---
output: html_document
---

<h2> Xu and Tenenbaum 2007b Replication </h2>
====
`r as.character(format(Sys.Date(), format="%B %d, %Y"))`
======


***
***

***
***

<a name="t1"/>
<h3> Turk Replication #1 </h3>

Read in data and pre-process.
```{r, echo =F}
d1 = read.csv("../data/turk_replication_3.csv")

# make factors
d1$Answer.sample <- factor(d1$Answer.sample, labels=c('teacher','learner')) # sample0= teacher, sample1=learner
d1$Answer.label <- factor(d1$Answer.label, labels=c('nolabel','label')) # 0=nolabel, 1=label

d1$Answer.Qwcheck <- factor(d1$Answer.Qwcheck)
d1$Answer.Qwsmm1 <- factor(d1$Answer.Qwsmm1)
d1$Answer.Qwsmm2 <- factor(d1$Answer.Qwsmm2)
d1$Answer.Qwsm1 <- factor(d1$Answer.Qwsm1)
d1$Answer.Qwsm2 <- factor(d1$Answer.Qwsm2)

d1$Answer.Qacheck <- factor(d1$Answer.Qacheck)
d1$Answer.Qasm1 <- factor(d1$Answer.Qasm1)
d1$Answer.Qasm2 <- factor(d1$Answer.Qasm2)
d1$Answer.Qasmm1 <- factor(d1$Answer.Qasmm1)
d1$Answer.Qasmm2 <- factor(d1$Answer.Qasmm2)
```

Filter.
```{r}
# subset data
d1 <- subset(d1, d1$Answer.label == 'label') # take out nolabel trials (study 4)
d1 <- subset(d1, !duplicated(d1$workerid)) # take out those who did it twice
d1 <- subset(d1, Answer.click1 == "\"correct\"" & Answer.click2 == "\"correct\"") # take out if selected wrong training items
d1 <- subset(d1, Answer.Qwcheck == 0) # take out if missed check generalization question
d1 <- subset(d1, Answer.question1 == 'true') # take out those who missed filter question
```


Categorize response patterns based on criterion.
```{r}
criterion = "unstrict1"  # category criterion

d1 <- d1[d1$Answer.label== "label",]
numsubj = dim(d1)[1]

if (criterion == "strict"){
  proper <- d1$Answer.Qwsmm1 == 0 & d1$Answer.Qwsmm2 == 0 & 
    (d1$Answer.Qwsm1 == 0 & d1$Answer.Qwsm2 == 0)
  sub <- d1$Answer.Qwsmm1 == 0 & d1$Answer.Qwsmm2 == 0 & 
    d1$Answer.Qwsm1 == 1 & d1$Answer.Qwsm2 == 1
  basic <- (d1$Answer.Qwsmm1 == 1 & d1$Answer.Qwsmm2 == 1) &
    d1$Answer.Qwsm1 == 1 & d1$Answer.Qwsm2 == 1 
  
} else if (criterion == "unstrict2"){
  proper <- d1$Answer.Qwsmm1 == 0 & d1$Answer.Qwsmm2 == 0 & 
    (d1$Answer.Qwsm1 == 0 & d1$Answer.Qwsm2 == 0)
  sub <- d1$Answer.Qwsmm1 == 0 & d1$Answer.Qwsmm2 == 0 & 
    (d1$Answer.Qwsm1 == 1 | d1$Answer.Qwsm2 == 1)
  basic <- (d1$Answer.Qwsmm1 == 1 | d1$Answer.Qwsmm2 == 1) &
    (d1$Answer.Qwsm1 == 1 & d1$Answer.Qwsm2 == 1)
  
} else if (criterion == "unstrict1"){
  proper <- d1$Answer.Qwsmm1 == 0 & d1$Answer.Qwsmm2 == 0 & 
    (d1$Answer.Qwsm1 == 0 | d1$Answer.Qwsm2 == 0)
  sub <- d1$Answer.Qwsmm1 == 0 & d1$Answer.Qwsmm2 == 0 & 
    d1$Answer.Qwsm1 == 1 & d1$Answer.Qwsm2 == 1
  basic <- (d1$Answer.Qwsmm1 == 1 | d1$Answer.Qwsmm2 == 1) &
    d1$Answer.Qwsm1 == 1 & d1$Answer.Qwsm2 == 1   	
  
} else if(criterion == "x&t"){
  sub <- d1$Answer.Qwsmm1 == 0 & d1$Answer.Qwsmm2 == 0 & 
    d1$Answer.Qwsm1 == 1 & d1$Answer.Qwsm2 == 1
  basic <- (d1$Answer.Qwsmm1 == 1 & d1$Answer.Qwsmm2 == 1) &
    d1$Answer.Qwsm1 == 1 & d1$Answer.Qwsm2 == 1 		
}
d1$w.ans.cat <- "other"
d1$w.ans.cat[sub] <- "sub"
d1$w.ans.cat[basic] <- "basic"
#d1$w.ans.cat[proper] <- "proper"
d1$w.ans.cat = factor(d1$w.ans.cat, levels=c("proper", "sub", "basic", "other"))
d1 = d1[d1$w.ans.cat != "other",]
# get proportions and bootstrapped CIS
M <- data.frame()

for (k in 1:length(levels(d1$w.ans.cat))){
    M = rbind(M, ddply(d1, .(Answer.sample), 
                     function (d) {getPs(d$w.ans.cat, levels(d$w.ans.cat)[k])}))
}
M$exp = "Turk #1"
```

Plot.


```{r, echo=F}
# plot
ggplot(data=M[M$dv == "basic" | M$dv == "sub",], aes(x=factor(dv), y=p, fill=Answer.sample)) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_linerange(aes(ymin=ciwl,ymax=ciul), position=position_dodge(.9)) +
  ylim(0,1) +
  ylab("Prop. participants showing \ngeneralization pattern") +
  xlab("Generalization pattern") +
  ggtitle("Turk Replication #2") +
  theme(text = element_text(size=18),
        plot.title=element_text(size=20, face = "bold"),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(color = 'black'),
        legend.position=c(.85,.8),
        panel.background = element_rect(fill = 'white', colour = 'white')) +
  scale_fill_discrete(name="Sampling\nCondition") 

```

Stats 
No difference.
```{r}
d1_counts= table(d1$w.ans.cat, d1$Answer.sample)[2:3,]
chisq.test(d1_counts)
```


<a name="t2"/>
<h3> Turk Replication #3 </h3>

Read in data and pre-process
```{r, echo = F}
#d2 <- read.csv("../data/turk_replication_3.csv",sep="\t",header=T)
d2 <- read.csv("/Documents/GRADUATE_SCHOOL/Projects/xtSamp/xt_2007b_replication/data/turk_replication_3.csv",sep="\t",header=T)

d2 <- d2[,c(-1:-19,-21:-32,-36,-41:-43,-54:-55,-56)] # remove unnecessary columns

# make factors
d2$Answer.sample <- factor(d2$Answer.sample, labels=c('teacher','learner')) # sample0 = teacher, sample1=learner

d2$Answer.Qcheck1 <- factor(d2$Answer.Qcheck1)
d2$Answer.Qcheck2 <- factor(d2$Answer.Qcheck2)

d2$Answer.Qsub1 <- factor(d2$Answer.Qsub1)
d2$Answer.Qsub2 <- factor(d2$Answer.Qsub2)

d2$Answer.Qbasic1 <- factor(d2$Answer.Qbasic1)
d2$Answer.Qbasic2 <- factor(d2$Answer.Qbasic2)
d2$Answer.Qbasic3 <- factor(d2$Answer.Qbasic3)

d2$Answer.Qproper1 <- factor(d2$Answer.Qproper1)
d2$Answer.Qproper2 <- factor(d2$Answer.Qproper2)
d2$Answer.Qproper3 <- factor(d2$Answer.Qproper3)
```

Filter.
```{r}
# subset data
d2 <- subset(d2, Answer.click1 == "\"correct\"" & Answer.click2 == "\"correct\"") # take out those who click on wrong training items
d2 <- subset(d2, Answer.Qcheck1 == 0 & Answer.Qcheck2 == 0) # take out if missed check generalization question
d2 <- subset(d2, Answer.question1 == 'true' & Answer.question2 =='true' & 
  Answer.question3 == 'true' & Answer.question4=='true' ) # take out those who missed filter question

```

Categorize response patterns based on criterion.
```{r}
criterion = "unstrictnew" 
numsubj = dim(d2)[1]

if (criterion == "unstrictold"){
  proper <- (d2$Answer.Qproper1 == 1 & d2$Answer.Qproper2 == 1 & 
  	d2$Answer.Qproper3 == 1) & d2$Answer.Qsub1 == 0 &
		d2$Answer.Qsub2 == 0 & d2$Answer.Qbasic1 == 0 &
		d2$Answer.Qbasic2 == 0 & d2$Answer.Qbasic3 == 0 
	sub <- 	d2$Answer.Qproper1 == 1 & d2$Answer.Qproper2 == 1 & 
		d2$Answer.Qproper3 == 1 & d2$Answer.Qsub1 == 1 &
		d2$Answer.Qsub2 == 1 & d2$Answer.Qbasic1 == 0 &
		d2$Answer.Qbasic2 == 0 & d2$Answer.Qbasic3 == 0 
	basic <- d2$Answer.Qproper1 == 1 & d2$Answer.Qproper2 == 1 & 
		d2$Answer.Qproper3 == 1 & d2$Answer.Qsub1 == 1 &
		d2$Answer.Qsub2 == 1 & d2$Answer.Qbasic1 == 1 &
		d2$Answer.Qbasic2 == 1 & d2$Answer.Qbasic3 == 1 
} else if (criterion == "unstrictnew") { 
	proper <- (d2$Answer.Qproper1 == 1 & d2$Answer.Qproper2 == 1 & 
		d2$Answer.Qproper3 == 1) & (d2$Answer.Qsub1 == 0 |
		d2$Answer.Qsub2 == 0) & d2$Answer.Qbasic1 == 0 &
		d2$Answer.Qbasic2 == 0 & d2$Answer.Qbasic3 == 0 
	sub <- 	d2$Answer.Qproper1 == 1 & d2$Answer.Qproper2 == 1 & 
		d2$Answer.Qproper3 == 1 & d2$Answer.Qsub1 == 1 &
		d2$Answer.Qsub2 == 1 & d2$Answer.Qbasic1 == 0 &
		d2$Answer.Qbasic2 == 0 & d2$Answer.Qbasic3 == 0 
	basic <- d2$Answer.Qproper1 == 1 & d2$Answer.Qproper2 == 1 & 
		d2$Answer.Qproper3 == 1 & d2$Answer.Qsub1 == 1 &
		d2$Answer.Qsub2 == 1 & (d2$Answer.Qbasic1 == 1 |
		d2$Answer.Qbasic2 == 1 | d2$Answer.Qbasic3 == 1)
} 

d2$w.ans.cat <- "other"
#d2$w.ans.cat[proper] <- "proper"
d2$w.ans.cat[sub] <- "sub"
d2$w.ans.cat[basic] <- "basic"
d2$w.ans.cat <- factor(d2$w.ans.cat,c("proper","sub","basic","other"))
d2 = d2[d2$w.ans.cat != "other",]
# get proportions and bootstrapped CIS
M2 <- data.frame()
for (k in 1:length(levels(d2$w.ans.cat))){
    M2 = rbind(M2, ddply(d2, .(Answer.sample), 
                     function (d) {getPs(d$w.ans.cat, levels(d$w.ans.cat)[k])}))
}
M2$exp = "Turk #2"
```

Plot.

```{r, echo=F}
# plot
ggplot(data=M2[M2$dv == "basic" | M2$dv == "sub",], aes(x=factor(dv), y=p, fill=Answer.sample)) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_linerange(aes(ymin=ciwl,ymax=ciul), position=position_dodge(.9)) +
  ylim(0,1) +
  ylab("Prop. participants showing \ngeneralization pattern") +
  xlab("Generalization pattern") +
  ggtitle("Turk Replication #3") +
  theme(text = element_text(size=18),
        plot.title=element_text(size=20, face = "bold"),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line(color = 'black'),
        legend.position=c(.85,.8),
        panel.background = element_rect(fill = 'white', colour = 'white')) +
  scale_fill_discrete(name="Sampling\nCondition")

```


Stats 
No difference.
```{r}
d2_counts= table(d2$w.ans.cat, d2$Answer.sample)[2:3,]
chisq.test(d2_counts)
```
